# -*- coding: utf-8 -*-
"""Signal_significance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTlSLLzH1RYB3bISHbdaGSrnGF2dd3Qw
"""

import numpy as np
import matplotlib.pyplot as plt
# s/ sqrt (S+B) = n sigma

for n in range(3,6):
    f = lambda x: (n*n+np.sqrt(n*n+4*n*x))/2
    xi=0
    xf=500
    point=100
    x = np.linspace(xi,xf,point)
    y= f(x)
    plt.plot(x,y,label="S= "+str(n)+"$ \sigma$ ")
    n=n+1
    plt.legend()
nSig_max=30
plt.plot([xi,xf], [nSig_max,nSig_max], linestyle='dotted')
plt.show()