# -*- coding: utf-8 -*-
"""RandomNumbers_multivariateGaussian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IoLVUnHlaLdrb9kixLojvrlrHOJTiY3T
"""

import numpy as np
import matplotlib.pyplot as plt

# example: 2d normal distribution
mu = np.array([10., 0.]) # mean
cov = np.array([[1, 0.7], [0.7 , 1]]) # cov. matrix

# Cholesky decomposition, A = lower triangular matrix
A = np.linalg.cholesky(cov)

# number of random vectors
n = 10000

# random numbers following standard normal distr.
# Ndim rows, N columns (here Ndim = 2)
z = np.random.normal(size=(2, n))

# matrix with Ndim rows (here Ndim = 2):
# [[mu1, mu1, ...], [mu2, mu2, ...]]
mean = np.repeat(mu, n).reshape(2,n)

# matrix of random vectors
# vector i: (rand[1][i], rand[2][i])
rand = mean + np.dot(A, z)

fig, ax = plt.subplots()
ax.set_aspect(1)
ax.set_xlim(5., 15.)
ax.set_ylim(-4. , 4.)
plt.plot(rand[0], rand[1], 'b.');