# -*- coding: utf-8 -*-
"""Error_Operations_on_two_independent_variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aK3iXTxXpZePmiC0QoUKzOCG22rO9rx

Evaluate the error of the sum of two uncorrelated variables
"""

import sympy as sp

x, dx = sp.symbols('x dx')
y, dy = sp.symbols('y dy')

z = x + y
dz = sp.sqrt(dx**2 + dy**2)

z_value = z.subs({x: 5, y: 10})
dz_value = dz.subs({dx: 0.1, dy: 0.2})

print("Sum (z):", z_value)
print("Uncertainty of the sum (dz):", dz_value)

"""Evaluate the error of the product of two uncorrelated variables"""

import sympy as sp

x, dx = sp.symbols('x dx')
y, dy = sp.symbols('y dy')

z = x * y
dz = sp.sqrt(y**2 * dx**2 + x**2 * dy**2)

z_value = z.subs({x: 5, y: 10})
dz_value = dz.subs({x: 5, y: 10 , dx: 0.1, dy: 0.2})

print("Product (z):", z_value)
print("Uncertainty of the product (dz):", dz_value)

"""Evaluate the error of the ratio of two uncorrelated variables"""

import sympy as sp

x, dx = sp.symbols('x dx')
y, dy = sp.symbols('y dy')

z = x / y
dz = sp.sqrt(1/y**2 * dx**2 + x**2/y**2 * dy**2)

z_value = z.subs({x: 5, y: 10})
dz_value = dz.subs({x: 5, y: 10 , dx: 0.1, dy: 0.2})

print("Ratio (z):", z_value)
print("Uncertainty of the ratio (dz):", dz_value)

import sympy as sp

x, dx = sp.symbols('x dx')
y, dy = sp.symbols('y dy')

z = x * sp.exp(y)

dz = sp.sqrt(sp.exp(y)**2 * dx**2 + x**2 * sp.exp(y)**2 * dy**2)

z_value = z.subs({x: 5, y: 10}).evalf()
dz_value = dz.subs({x: 5, y: 10 , dx: 0.1, dy: 0.2}).evalf()

print("x * exp(y) = (z):", z_value)
print("Uncertainty on z (dz):", dz_value)